vnc executor
ait-testbed/attackmate pull request #129
Opened 2024-10-17 08:04 UTC by thorinaboenke

- adds a vnc executor

2025-02-11 15:11 UTC, thorinaboenke commented
requested: im schema vom vncexecutor einbauen, dass eine fehlermeldung ausgegeben wird wenn jemand den background-mode mit dem vncexecutor verwendet

2025-02-13 09:24 UTC, whotwagner requested changes

2025-02-13 09:24 UTC, whotwagner commented on src/attackmate/executors/vnc/vncexecutor.py
> +        time.sleep(5)
can we somehow avoid this sleep?

2025-02-13 09:24 UTC, whotwagner commented on src/attackmate/executors/vnc/vncexecutor.py
> +    def cache_settings(self, command: VncCommand):
I think we don't need the cache for the vnc-executor. (I even believe that we might remove it at some point from the sshexecutor too)

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +   vnc-command was executed with the command-option "creates_session"
```suggestion
   vnc-command was executed with the command-option ``creates_session``
```

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +   y position ot move the cursor to ``move``
```suggestion
   y position to move the cursor to with the command ``move``
```

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +   x position ot move the cursor to with the command ``move``
```suggestion
   x position to move the cursor to with the command ``move``
```

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +   Metric to compare a screen with ``expext screen``. Only continue if the sceen matches.
```suggestion
   Metric to compare a screen with ``expectscreen``. Only continue if the screen matches.
```

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +   Path where a screeshot ``capture`` should be saved, or file to compare a screenshot with ``expext screen``.
```suggestion
   Path where a screenshot ``capture`` should be saved, or file to compare a screenshot with ``expectscreen``.
```

2025-02-13 11:53 UTC, annaerdi commented on docs/source/playbook/commands/vnc.rst
> +Execute commands on a remote server via VNC. Uses the `vncdotool <https://github.com/sibson/vncdotool>` library.
```suggestion
Execute commands on a remote server via VNC. Uses the `vncdotool <https://github.com/sibson/vncdotool>`_ library.
```

2025-02-13 13:15 UTC, annaerdi commented
When the `expectscreen` command doesn't match, attackmate just keeps hanging at this step forever without any warning/info message. Maybe adding a graceful exit for this case would be nice

2025-02-13 13:37 UTC, annaerdi commented on src/attackmate/executors/vnc/sessionstore.py
> +            return False
```suggestion
        return session_name in self.store
```

2025-02-17 11:54 UTC, thorinaboenke commented on src/attackmate/executors/vnc/vncexecutor.py
> +    def cache_settings(self, command: VncCommand):
removed

2025-02-17 12:08 UTC, thorinaboenke commented
> When the `expectscreen` command doesn't match, attackmate just keeps hanging at this step forever without any warning/info message. Maybe adding a graceful exit for this case would be nice

From what I gather the libraries expectscreen is to halt execution until the screen matches the expected. Down the line it calls the function _expectCompare in client.py, which  returns a Deferred that never times out, i.e. it just adds a callback to try again https://github.com/sibson/vncdotool/blob/ec3f4815305db4c0eb28510a628cf912a010a783/vncdotool/client.py

2025-02-17 13:19 UTC, thorinaboenke commented
Now i can 1) check if the result is None, and log the failure -> expect screen still blocks further execution. 2) i can run client.expectscreen in s separate thread and log failure if it is still alive after a timeout period --> if there is no match this thread will never terminate on its own. I am open to suggestions how to tell the vnc client "from the outside" to stop waiting for the expect screen

2025-02-18 10:10 UTC, whotwagner approved these changes

2025-02-18 10:10 UTC, merged